services:
  db-backup:
    image: prodrigestivill/postgres-backup-local
    container_name: ardua-db-backup
    depends_on:
      - db
    env_file:
      - .env
      - .env.backup
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

      SCHEDULE: "@daily"
      
      BACKUP_KEEP_DAYS: 14
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 3

      BACKUP_SUFFIX: .dump
      S3_PREFIX: postgres
  restart: unless-stopped


  receipts-backup:
    image: rclone/rclone:latest
    container_name: ardua-receipts-backup
    volumes:
      - media_volume:/data:ro
      - ./rclone:/config/rclone
    command: >
      sh -c "
      while true; do
        rclone sync /data/receipts s3:ardua-books-backups/receipts \
          --config /config/rclone/rclone.conf \
          --checksum \
          --verbose;
          sleep 86400;
        done
      "
    restart: unless-stopped