# Generated by Django 5.2.8 on 2025-12-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_add_cash_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentapplication",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="paymentapplication",
            name="invoice",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="PaymentApplication",
        ),
    ]
