# Generated by Django 5.2.8 on 2025-12-05 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_payment_paymentapplication"),
        ("billing", "0002_alter_invoiceline_line_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentapplication",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="billing.invoice"
            ),
        ),
    ]
