# Generated by Django 5.2.8 on 2025-12-09 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_bankaccount_banktransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="offset_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_transactions_offset",
                to="accounting.chartofaccount",
            ),
        ),
    ]
