# Generated by Django 5.2.8 on 2025-12-09 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_banktransaction_offset_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankImportProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_column_index", models.PositiveSmallIntegerField()),
                ("description_column_index", models.PositiveSmallIntegerField()),
                ("amount_column_index", models.PositiveSmallIntegerField()),
                (
                    "date_format",
                    models.CharField(
                        default="%Y-%m-%d",
                        help_text="Python strptime format, e.g. %m/%d/%Y",
                        max_length=50,
                    ),
                ),
                (
                    "sign_rule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BANK_STANDARD", "Bank: + deposit, - withdrawal"),
                            (
                                "CC_CHARGES_POSITIVE",
                                "Credit card: + charge, - payment (Amex)",
                            ),
                            (
                                "CC_CHARGES_NEGATIVE",
                                "Credit card: - charge, + payment (Chase)",
                            ),
                        ],
                        help_text="For bank accounts this is auto-assigned.",
                        max_length=30,
                    ),
                ),
                (
                    "skip_if_description_contains",
                    models.CharField(
                        blank=True,
                        help_text="If set, skip rows whose description contains this phrase.",
                        max_length=200,
                    ),
                ),
                (
                    "bank_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_profile",
                        to="accounting.bankaccount",
                    ),
                ),
            ],
        ),
    ]
