# Generated by Django 5.2.8 on 2025-12-09 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_bankimportprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                help_text="If this bank transaction has been matched to a payment, it appears here.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transactions",
                to="accounting.payment",
            ),
        ),
    ]
