# Generated by Django 5.2.8 on 2025-12-12 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0011_banktransaction_payment"),
        ("billing", "0003_invoice_sequence_alter_invoice_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transactions",
                to="billing.expense",
            ),
        ),
    ]
