# Generated by Django 5.2.8 on 2025-12-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0012_banktransaction_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="transfer_pair",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfer_linked",
                to="accounting.banktransaction",
            ),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transactions",
                to="accounting.journalentry",
            ),
        ),
    ]
