# Generated by Django 5.2.8 on 2026-04-17 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0014_create_viewer_group"),
        ("billing", "0006_recurring_charges"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description_contains",
                    models.CharField(
                        help_text="Case-insensitive substring to match against transaction description.",
                        max_length=200,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher values are evaluated first."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to match transactions from any bank account.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction_rules",
                        to="accounting.bankaccount",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction_rules",
                        to="billing.expensecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "name"],
            },
        ),
    ]
