# Generated by Django 5.2.8 on 2025-11-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceline",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("TIME", "Time entry"),
                    ("EXPENSE", "Expense"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("GENERAL", "General line"),
                ],
                max_length=20,
            ),
        ),
    ]
