# Generated by Django 5.2.8 on 2025-12-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_alter_invoiceline_line_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="sequence",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                blank=True, help_text="e.g. 2025-001", max_length=50, unique=True
            ),
        ),
    ]
