# Generated by Django 5.2.8 on 2025-12-16 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0012_banktransaction_expense"),
        ("billing", "0003_invoice_sequence_alter_invoice_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="payment_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Bank account used to pay this expense",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="GL expense account for this category",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.chartofaccount",
            ),
        ),
    ]
