# Generated by Django 5.2.8 on 2025-12-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_add_expense_gl_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "address",
                    models.TextField(blank=True, help_text="Full mailing address"),
                ),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "verbose_name_plural": "Company",
            },
        ),
    ]
