# Generated by Django 5.2.8 on 2026-02-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_add_company_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceline",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("TIME", "Time entry"),
                    ("EXPENSE", "Expense"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("GENERAL", "General line"),
                    ("RECURRING", "Recurring charge"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RecurringCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for an indefinite recurring charge.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_billed_date",
                    models.DateField(
                        blank=True,
                        help_text="Automatically updated when this charge is added to an invoice.",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_charges",
                        to="billing.client",
                    ),
                ),
            ],
            options={
                "ordering": ["client__name", "description"],
            },
        ),
        migrations.CreateModel(
            name="RecurringChargeOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_billed", models.DecimalField(decimal_places=2, max_digits=10)),
                ("occurrence_date", models.DateField()),
                (
                    "invoice_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_charge_occurrence",
                        to="billing.invoiceline",
                    ),
                ),
                (
                    "recurring_charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occurrences",
                        to="billing.recurringcharge",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurrence_date"],
            },
        ),
    ]
